version: '3.4'

services:
  lhservice:
    image: lasso:1.0
    volumes:
      - ${GCP_KEY_PATH}:/env/gcp-keyfile.json:ro
    restart: always
    working_dir: /app
    #command: sh -c "npm install && npm start"
    ports:
      - "8080:${PORT:-8080}"
    environment:
      PORT: ${PORT:-8080}
      K_SERVICE: lasso
      K_REVISION: 0
      K_CONFIGURATION: lasso
      BQ_DATASET: lh_results
      BQ_TABLE: lh_set
      GOOGLE_APPLICATION_CREDENTIALS: /env/gcp-keyfile.json
      GOOGLE_CLOUD_PROJECT: 'elite-life-385102'
      CLOUD_TASKS_QUEUE: 'lhtests'
      CLOUD_TASKS_QUEUE_LOCATION: 'europe-west8'
      SERVICE_URL: ${SERVICE_URL}